package app.softnetwork.notification.api

import app.softnetwork.persistence.jdbc.query.PostgresSchemaProvider

object AllNotificationsPostgresLauncher extends AllNotificationsApi with PostgresSchemaProvider
